---
name: Compile LaTeX files to PDF
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
  workflow_call: # to reuse by release workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code.
      uses: actions/checkout@v4
      
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags

    - name: get Git tag info
      run: |
        echo "\\def\\gitTag{`git describe --tags || echo 'no-tag'`}" >> gitinfo.tex

    - name: Build PDFs.
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          Einzug.tex
          Aufnahmeantrag_aktiv.tex
          Aufnahmeantrag_foerder_nat.tex
          Aufnahmeantrag_foerder_jur.tex

    - name: Upload PDFs.
      uses: actions/upload-artifact@v4
      with:
        name: PDFs
        path: "*.pdf"
        retention-days: 5
        if-no-files-found: error
